name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: echo ENV
    - run: ls
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.0.1
      with:
        args: "deploy"
      env:
        PROJECT_ID: "thomas-sickert-website"
        FIREBASE_TOKEN: 1/CVMfnV5VTh-5AH0HL87KFGTQrMxvGAddkkG9nrznUlQ

