name: CI

on: [push]

jobs:
  deploy:
    steps:
    - name: GitHub Action for Firebase
      uses: w9jds/firebase-action@v1.0.1
      with:
        args: "deploy"
      env:
        PROJECT_ID: "thomas-sickert-website"
      secrets: ["1/CVMfnV5VTh-5AH0HL87KFGTQrMxvGAddkkG9nrznUlQ"]
